SELECT TABL_INVENTARIO.ID_INVENTARIO, 
TABL_PARCELAS.ID_PARCELA, 
TABL_VISITAS.ID_VISITA, 
DICC_COTAS.COTA, 
DICC_ENTIDADES.TAXON, 
TABL_INVENTARIO.COD_TAXON, 
TABL_VISITAS.FECHA, 
'BORREG' & '-' & Format([ID_PARCELA],"000") & '-' & Format([ID_VISITA],"000000") & '-' & Format([ID_INVENTARIO],"000000000") AS idGBIF,
TABL_INVENTARIO.NUM_ESTRCT_FLORALES, TABL_INVENTARIO.NUM_FRUTOS FROM ((DICC_COTAS INNER JOIN TABL_PARCELAS ON DICC_COTAS.ID_COTA = TABL_PARCELAS.COD_COTA) INNER JOIN TABL_VISITAS ON TABL_PARCELAS.ID_PARCELA = TABL_VISITAS.COD_PARCELA) INNER JOIN (DICC_ENTIDADES INNER JOIN TABL_INVENTARIO ON DICC_ENTIDADES.ID_TAXON = TABL_INVENTARIO.COD_TAXON) ON TABL_VISITAS.ID_VISITA = TABL_INVENTARIO.COD_VISITAWHERE (((TABL_INVENTARIO.COD_TAXON)>0))ORDER BY TABL_VISITAS.FECHA;