---
title: Compute taxa numbers
author: ajpelu
output:
    md_document:
      variant: markdown_github
---



# Count Phylum 
```{r}
phy <- data.frame(phy=c('Magnoliophyta', 'Pteridophyta'),
                   count=c(10939,63))
phy$per <- round((phy$count/sum(phy$count))*100, 3)
phy 
```


# Count class
```{r}
clas <- data.frame(cl=c('Liliposida', 'Magnoliopsida', 'Psilotopsida'),
                   count=c(4882,6057,63))
clas$per <- round((clas$count/sum(clas$count))*100, 3)
clas
```


# Count order
```{r}
di <- '/Users/ajpelu/Dropbox/MS/MS_DP_Borreguiles/git/BorreguilesDP/9_submission/revision_1/data' 
ord <- read.table(file=paste(di, '/order.txt', sep=''), header=T, sep='\t')

ord$per <- round((ord$CuentaDeorder/sum(ord$CuentaDeorder))*100,3)

```


# Count family
```{r}
di <- '/Users/ajpelu/Dropbox/MS/MS_DP_Borreguiles/git/BorreguilesDP/9_submission/revision_1/data' 
fam <- read.table(file=paste(di, '/family.txt', sep=''), header=T, sep='\t')

fam$per <- round((fam$CuentaDefamily/sum(fam$CuentaDefamily))*100,3)

```
